---
- hosts: my-servers
  become: yes
  tasks:
    - name: Make sure we can connect
      ping:
    - name: Add the ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php'
    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install PHP
      apt: name={{item}} state=installed
      with_items:
        - php
        - php-fpm
        - php-mysql
        - php-xml
    - name: Remove apache2
      apt: name=apache2 state=removed
    # MySQL
    - name: Install MySQL
      apt: name={{item}} state=installed
      with_items:
        - mysql-server-5.7
        - python-mysqldb
    - name: Generate new root password for mysql
      command: openssl rand -hex 7 creates=/root/.my.cnf
      register: mysql_new_root_password
    - name: Remove anonymous users
      mysql_user: name="" state=absent 
      when: mysql_new_root_password.changed
    - name: Remove test database
      mysql_db: name=test state=absent
      when: mysql_new_root_password.changed
    - name: Output new root password
      debug: msg="New root password is {{mysql_new_root_password}}"
      when: mysql_new_root_password.changed
    - name: Update root password
      mysql_user: name=root host={{item}} password="{{mysql_new_root_password.stdout}}"
      with_items:
        - "{{ansible_hostname}}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_password.changed 
    - name: Create my.cnf
      template: src=templates/mysql/my.cnf dest=/root/.my.cnf
      when: mysql_new_root_password.changed 

